### ISSUE TITLE
[Bug]: Beep log counter reset

### ISSUE THREAD

**Issue by skoch13** [chrisgrieser/nvim-chainsaw#5]
### Bug Description

Thank you for this useful plugin! 

When removing beep logs manually the counter is not reset before `removeLogs()` is called.

edit: same bug applicable to `timeLog`

### To Reproduce

1. Open any file, e.g.`example.ts`
2. Add beep statement - 1️⃣ is added
3. Remove the line with `dd`
4. Add another beep statement: 2️⃣ is added

### neovim version

```Text
0.9.5
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Hi, I think this is simply a misunderstanding brought by the number emojis. `beepLog` isn't supposed to be any sort of counter, but only to indicate whether certain "control paths" (if-else-routes) have been taken. As such, the numbered emojis are a bit misleading, the role of the `beepEmojis` is just to make the beep-log-statements distinguishable.

The counter-reset is actually not even necessary. Before yesterday's change, emojis were selected randomly, which unfortunately sometimes resulted in the same emojis being inserted in a row, which was contrary to the purpose of making them distinguishable. That's why I changed it to sequentially go through the list of emojis. I changed the default emojis to avoid that misunderstanding.

**Comment by chrisgrieser** [comment]
yeah, timeLogs in general need improvements, as for example multiple timeLogs in one file do not work (two times declaring the same variable and so on…)

Could you open a FR/bug report for all such issues with timeLog, since considering the other problems of timeLog, it's straying a bit far from the original issue?

(Though I have to admit it's currently not high priority to implement, since I am not using timeLog much.)

**Comment by chrisgrieser** [comment]
Earlier today, I improved the behavior of `beepLog` to prioritize emojis that have not been used yet, this might also address this issue you originally had
