### ISSUE TITLE
Feature Request: (Potentially) Better log line deletion with marks

### ISSUE THREAD

**Issue by SystematicError** [chrisgrieser/nvim-chainsaw#7]
### Feature Requested

Neovim has a great feature called [marks](https://vim.fandom.com/wiki/Using_marks), which essentially act like "bookmarks" for lines. Once you mark a line, you can quickly jump to the mark in one motion.

If chainsaw marked every log line, it would make operations such as deletion easier on these lines. This could help prevent unintentionally deleting actual code which for whatsoever reason includes your marker substring.

Markers behave pretty logically most of the time, the mark moves with the text (if you were to prepend some lines of text before the log line for example), and the mark also gets deleted if you were to delete the line of text using `dd`. **However**, I did find one edge case, if i marked a line and then deleted it by going into insert and backspacing away the whole line, the mark shifts onto the line of code below it, ending up marking the wrong line.

I'm personally not super well versed with marks and the nvim lua api, so I'm not too sure how exactly to avoid such edgecases, but if implemented correctly marks have the potential to make bulk operations on log lines more efficient and robust.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I also thought about using marks (or rather, [extmarks](https://neovim.io/doc/user/api.html#api-extmark)), but decided against it, for several reasons:
1. reliability: as you stated, there are some cases where marks can get deleted. This not only includes the edge case you are describing, but also various vim commands (certain formatting plugins, `:delmarks`, `:bwipeout`, …). As such, marks are just not reliable enough.
2. transparency: with a marker, it is at glance transparent to the user which log statements are from chainsaw and which are log statements intended to stay.
3. portability: If you switch to a different editor, or to a different machine without somehow syncing your shada, this information is lost. String markers have the advantage of working reliably here as well.
4. interoperability: (ext)marks are a vim-exclusive feature. In contrast, "delete lines with string x" is a fairly common operation, which you can execute in pretty much any editor more advanced than notepad/textedit. Some editors also have dedicated extensions that work similarly, such as [Turbo console log for VS Code](https://marketplace.visualstudio.com/items?itemName=ChakrounAnas.turbo-console-log). Using string markers, nvim-chainsaw is pretty much compatible with those other plugins, allowing you to use this plugin collaboratively with others.

As such, the advantages of using string markers outweigh the disadvantages by far in my view, which is why I settled on string markers.

> unintentionally deleting actual code which for whatsoever reason includes your marker substring.

This problem case can be dealt with by simply using a unique string as marker. And even if you work with some arcane file which includes all existing emojis, there are special characters, or a combination of characters you could use.
